version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
    - "6379:6379"
  api:
    build: .
    command: uvicorn api.http_endpoint:app --host 0.0.0.0
    environment:
    - "REDIS_HOST=redis"
    - "REDIS_PORT=6379"
    - "REDIS_DB=1"
    links:
      - redis
    ports:
      - "8000:8000"

